name: "Build Pipeline"
on:
  workflow_dispatch:
jobs:
  Build:   
    runs-on: ubuntu-latest
    steps:
      - name: "Check out Git repository"
        uses: actions/checkout@v4    
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3      
      - name: Build Docker image
        run: |
          docker build -t juice-shop-app:latest .  
      
  
