name: "CI/CD Pipeline"
on:
  workflow_dispatch:
 
env:
  NODE_DEFAULT_VERSION: 20
  CYCLONEDX_NPM_VERSION: '^1.12.0'
  NODE_OPTIONS: "--max_old_space_size=4096"
jobs:


  docker:   
    runs-on: ubuntu-latest
    steps:
      - name: "Check out Git repository"
        uses: actions/checkout@4    
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker image
        run: |
          docker build -t juice-shop-app:latest .  
      
  
